### ISSUE TITLE
Missing code to `create_dependency(...)`

### ISSUE THREAD

**Issue by schloerke** [DivadNojnarg/outstanding-shiny-ui#76]
https://github.com/DivadNojnarg/outstanding-shiny-ui/blob/ba9293faeb17d142bd5d83dfe0cc72e62c64ad88/workflow-charpente.Rmd#L370-L374

The code in 373 is missing on how to install the dependency.

**Comment by schloerke** [comment]
Calling `create_dependency("@vizuaalog/bulmajs")` creates and error

```
❯❯ create_dependency("@vizuaalog/bulmajs")
ℹ Trying with https://data.jsdelivr.com/v1/package/npm/@vizuaalog/bulmajs
✔ Success!
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error in create_dependency("@vizuaalog/bulmajs") :
  No assets found for @vizuaalog/bulmajs
```

**Comment by DivadNojnarg** [comment]
Thanks for pointing this out. I believe something changed between version 0.12.1 and https://www.jsdelivr.com/package/npm/@vizuaalog/bulmajs?version=0.11.0 (the one for which I run the book). Let me add a note to specify the version and guaranty it works. I'll check later what's wrong in `{charpente}`.

**Comment by DivadNojnarg** [comment]
Overall, this example suffers from a lack of guidance. The first step is always to check `get_dependency_assets("@vizuaalog/bulmajs", tag = "0.11.0")` to see the repository structure. Since charpente make some preliminary assumptions, this may cause issue. For instance, we assume the repo contains minified assets, which is not always the case, especially for bulmaJS.
